/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viajes;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Container;
import java.awt.FlowLayout;
import static java.lang.Thread.sleep;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import viajes.listas.Cola;
import viajes.listas.ListaSimple;
import viajes.listas.*;
import viajes.modulos.*;
import java.io.*;
import java.util.logging.*;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import viajes.Travels;
import viajes.grafica.Carga;
import viajes.grafica.Carga;
/**
 *
 * @author HPBEATS
 */
public class Travels extends javax.swing.JFrame {
     MCarga carga = new MCarga();
        public Cola reservaciones = new Cola("reservaciones");
    public ListaSimple transporte = new ListaSimple("transporte");
    public ListaSimple asiento = new ListaSimple("asiento");
    public ListaSimple hoteles = new ListaSimple("hoteles");
    public ListaSimple habitacion = new ListaSimple("habitacion");
    public ListaSimple cruceros = new ListaSimple("cruceros");
    public ListaSimple camarot = new ListaSimple("camarot");
    public ListaSimple renta = new ListaSimple("renta_autos");
    public ListaSimple destinos = new ListaSimple("destinos");
    public ListaSimple lugares = new ListaSimple("lugares");
    public ListaSimple clientes = new ListaSimple("clientes");
    public ListaSimple entidad = new ListaSimple("entidad");
    public ListaSimple paquetes = new ListaSimple("paquetes"); 
    
    public String pathTransporte;
    public String pathAsiento;
    public String pathHoteles;
    public String pathHabitacion;
    public String pathCrucero;
    public String pathCamarot;
    public String pathDestino;
    public String pathLugar;
    public String pathRenta;
    public String pathClientes;
    public String pathEntidad;
    public String pathPaquetes;
    public String pathReservas;

//    private Carga carga;
    
    /**
     * Creates new form Travels
     */
    public Travels() {
        initComponents();
        jTabbedPane1.setSelectedIndex(2);
        jTabbedPane2.setSelectedIndex(0);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton14 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextField22 = new javax.swing.JTextField();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();

        jButton14.setText("jButton14");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        setBackground(new java.awt.Color(153, 255, 153));
        setFocusable(false);
        setOpacity(1);

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Presione un botón y cargue el archivo correspondiente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 13), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel4.setMinimumSize(new java.awt.Dimension(200, 450));
        jPanel4.setPreferredSize(new java.awt.Dimension(250, 450));
        jPanel4.setLayout(new java.awt.GridLayout(13, 0, 0, 5));

        jButton2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton2.setText("Aerolineas y Buses");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);

        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setText("Asiento");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);

        jButton3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton3.setText("Hoteles");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3);

        jButton4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton4.setText("Habitación");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4);

        jButton5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton5.setText("Destino Turistico");
        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5);

        jButton6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton6.setText("Lugar E&E");
        jButton6.setEnabled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6);

        jButton7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton7.setText("Cruceros");
        jButton7.setEnabled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton7);

        jButton8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton8.setText("Camarot");
        jButton8.setEnabled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton8);

        jButton9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton9.setText("Paquetes");
        jButton9.setEnabled(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton9);

        jButton10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton10.setText("Clientes");
        jButton10.setEnabled(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton10);

        jButton11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton11.setText("Renta Autos");
        jButton11.setEnabled(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton11);

        jButton12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton12.setText("Reservaciones");
        jButton12.setEnabled(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton12);

        jButton13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton13.setText("Entidad Financiera");
        jButton13.setEnabled(false);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton13);

        jTabbedPane1.addTab("CARGA", jPanel4);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Reservación"));
        jPanel3.setLayout(new java.awt.GridLayout(5, 2, 0, 10));

        jLabel1.setText("Paquete");
        jPanel3.add(jLabel1);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField1);

        jLabel2.setText("Fecha de Salida");
        jPanel3.add(jLabel2);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField2);

        jLabel3.setText("Cantidad días del viaje");
        jPanel3.add(jLabel3);
        jPanel3.add(jTextField3);

        jLabel4.setText("Costo Paquete");
        jPanel3.add(jLabel4);
        jPanel3.add(jTextField4);

        jButton15.setText("Limpiar Campos");
        jPanel3.add(jButton15);

        jButton16.setText("Reservar");
        jPanel3.add(jButton16);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Cliente"));
        jPanel6.setLayout(new java.awt.GridLayout(8, 2, 0, 10));

        jLabel9.setText("Código Cliente");
        jPanel6.add(jLabel9);

        jTextField9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField9FocusLost(evt);
            }
        });
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel6.add(jTextField9);

        jLabel10.setText("Nombre Cliente");
        jPanel6.add(jLabel10);

        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel6.add(jTextField10);

        jLabel11.setText("Número de Tarjeta");
        jPanel6.add(jLabel11);
        jPanel6.add(jTextField11);

        jLabel12.setText("Telefono");
        jPanel6.add(jLabel12);
        jPanel6.add(jTextField12);

        jLabel13.setText("Celular");
        jPanel6.add(jLabel13);
        jPanel6.add(jTextField13);

        jLabel14.setText("Domicilio");
        jPanel6.add(jLabel14);
        jPanel6.add(jTextField14);

        jLabel15.setText("Frecuencia por Viajes");
        jPanel6.add(jLabel15);
        jPanel6.add(jTextField15);

        jLabel16.setText("Frecuencia por Monto");
        jPanel6.add(jLabel16);
        jPanel6.add(jTextField16);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("RESERVACIONES", jPanel2);

        jTabbedPane2.setToolTipText("");

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Cliente"));
        jPanel8.setLayout(new java.awt.GridLayout(9, 2, 0, 10));

        jLabel17.setText("Código Cliente");
        jPanel8.add(jLabel17);

        jTextField17.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField17FocusLost(evt);
            }
        });
        jTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField17ActionPerformed(evt);
            }
        });
        jPanel8.add(jTextField17);

        jLabel5.setText("Nombre Cliente");
        jPanel8.add(jLabel5);
        jPanel8.add(jTextField5);

        jLabel18.setText("Apellido Cliente");
        jPanel8.add(jLabel18);

        jTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField18ActionPerformed(evt);
            }
        });
        jPanel8.add(jTextField18);

        jLabel19.setText("Número de Tarjeta");
        jPanel8.add(jLabel19);
        jPanel8.add(jTextField19);

        jLabel6.setText("Fecha de Nacimiento (dd/MM/yyyy)");
        jPanel8.add(jLabel6);
        jPanel8.add(jTextField6);

        jLabel20.setText("Telefono");
        jPanel8.add(jLabel20);
        jPanel8.add(jTextField20);

        jLabel21.setText("Celular");
        jPanel8.add(jLabel21);
        jPanel8.add(jTextField21);

        jLabel22.setText("Domicilio");
        jPanel8.add(jLabel22);
        jPanel8.add(jTextField22);

        jButton17.setText("Limpiar");
        jPanel8.add(jButton17);

        jButton18.setText("Guardar");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton18);

        jTabbedPane2.addTab("CLIENTES", jPanel8);

        jPanel9.setLayout(new java.awt.GridLayout(6, 2, 0, 10));
        jTabbedPane2.addTab("ENTIDAD FINANCIERA", jPanel9);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        jTabbedPane1.addTab("NEGOCIOS", jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            File file = carga.openFile();

            if (file!=null){
                pathTransporte = file.getAbsolutePath();
                carga.fillList(file, transporte);
                this.jButton2.setEnabled(false);
                this.jButton2.setIcon(new ImageIcon(getClass().getResource("exito.png")));
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "No se cargo el archivo","MODULO DE CARGA",JOptionPane.ERROR_MESSAGE);
            //            Logger.getLogger(Carga.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            File file = carga.openFile();
            if (file!=null){
                pathAsiento = file.getAbsolutePath();
                carga.fillList(file, asiento);
                this.jButton1.setEnabled(false);
                this.jButton1.setIcon(new ImageIcon(getClass().getResource("exito.png")));
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "No se cargo el archivo","MODULO DE CARGA",JOptionPane.ERROR_MESSAGE);
            //            Logger.getLogger(Carga.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            File file = carga.openFile();
            if (file!=null){
                pathHoteles= file.getAbsolutePath();
                carga.fillList(file, hoteles);
                this.jButton3.setEnabled(false);
                this.jButton3.setIcon(new ImageIcon(getClass().getResource("exito.png")));
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "No se cargo el archivo","MODULO DE CARGA",JOptionPane.ERROR_MESSAGE);
            //            Logger.getLogger(Carga.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
            File file = carga.openFile();
            if (file!=null){
                pathHabitacion= file.getAbsolutePath();
                carga.fillList(file, habitacion);
                this.jButton4.setEnabled(false);
                this.jButton4.setIcon(new ImageIcon(getClass().getResource("exito.png")));
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "No se cargo el archivo","MODULO DE CARGA",JOptionPane.ERROR_MESSAGE);
            //            Logger.getLogger(Carga.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            File file = carga.openFile();
            if (file!=null){
                pathDestino= file.getAbsolutePath();
                carga.fillList(file, destinos);
                this.jButton5.setEnabled(false);
                this.jButton5.setIcon(new ImageIcon(getClass().getResource("exito.png")));
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "No se cargo el archivo","MODULO DE CARGA",JOptionPane.ERROR_MESSAGE);
            //            Logger.getLogger(Carga.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            File file = carga.openFile();
            if (file!=null){
                pathLugar = file.getAbsolutePath();
                carga.fillList(file, lugares);
                this.jButton6.setEnabled(false);
                this.jButton6.setIcon(new ImageIcon(getClass().getResource("exito.png")));
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "No se cargo el archivo","MODULO DE CARGA",JOptionPane.ERROR_MESSAGE);
            //            Logger.getLogger(Carga.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try {
            File file = carga.openFile();
            if (file!=null){
                pathCrucero= file.getAbsolutePath();
                carga.fillList(file, cruceros);
                this.jButton7.setEnabled(false);
                this.jButton7.setIcon(new ImageIcon(getClass().getResource("exito.png")));
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "No se cargo el archivo","MODULO DE CARGA",JOptionPane.ERROR_MESSAGE);
            //            Logger.getLogger(Carga.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        try {
            File file = carga.openFile();
            if (file!=null){
                pathCamarot= file.getAbsolutePath();
                carga.fillList(file, camarot);
                this.jButton8.setEnabled(false);
                this.jButton8.setIcon(new ImageIcon(getClass().getResource("exito.png")));
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "No se cargo el archivo","MODULO DE CARGA",JOptionPane.ERROR_MESSAGE);
            //            Logger.getLogger(Carga.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            File file = carga.openFile();
            if (file!=null){
                pathPaquetes= file.getAbsolutePath();
                carga.fillList(file, paquetes);
                this.jButton9.setEnabled(false);
                this.jButton9.setIcon(new ImageIcon(getClass().getResource("exito.png")));
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "No se cargo el archivo","MODULO DE CARGA",JOptionPane.ERROR_MESSAGE);
            //            Logger.getLogger(Carga.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            File file = carga.openFile();
            if (file!=null){
                pathClientes= file.getAbsolutePath();
                carga.fillList(file, clientes);
                this.jButton10.setEnabled(false);
                this.jButton10.setIcon(new ImageIcon(getClass().getResource("exito.png")));
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "No se cargo el archivo","MODULO DE CARGA",JOptionPane.ERROR_MESSAGE);
            //            Logger.getLogger(Carga.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        try {
            File file = carga.openFile();
            if (file!=null){
                pathRenta= file.getAbsolutePath();
                carga.fillList(file,renta);
                this.jButton11.setEnabled(false);
                this.jButton11.setIcon(new ImageIcon(getClass().getResource("exito.png")));
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "No se cargo el archivo","MODULO DE CARGA",JOptionPane.ERROR_MESSAGE);
            //            Logger.getLogger(Carga.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            File file = carga.openFile();
            if (file!=null){
                pathReservas = file.getAbsolutePath();
                carga.llenarCola(file, reservaciones);
                this.jButton12.setEnabled(false);
                this.jButton12.setIcon(new ImageIcon(getClass().getResource("exito.png")));
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "No se cargo el archivo","MODULO DE CARGA",JOptionPane.ERROR_MESSAGE);
            //            Logger.getLogger(Carga.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            File file = carga.openFile();
            if (file!=null){
                pathEntidad= file.getAbsolutePath();
                carga.fillList(carga.openFile(), entidad);
                this.jButton13.setEnabled(false);
                this.jButton13.setIcon(new ImageIcon(getClass().getResource("exito.png")));
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "No se cargo el archivo","MODULO DE CARGA",JOptionPane.ERROR_MESSAGE);
            //            Logger.getLogger(Carga.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
        if (jTabbedPane1.getSelectedIndex()==0){
            JPasswordField pf = new JPasswordField();
            int okCxl = JOptionPane.showConfirmDialog(null, pf, "Contraseña Administrador", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

            if (okCxl == JOptionPane.OK_OPTION) {
                Container cp = this.getContentPane();
                String password = new String(pf.getPassword());
                if (password.equals("0000")){
                    this.jButton1.setEnabled(true);
                    this.jButton10.setEnabled(true);
                    this.jButton11.setEnabled(true);
                    this.jButton12.setEnabled(true);
                    this.jButton13.setEnabled(true);
                    this.jButton2.setEnabled(true);
                    this.jButton3.setEnabled(true);
                    this.jButton4.setEnabled(true);
                    this.jButton5.setEnabled(true);
                    this.jButton6.setEnabled(true);
                    this.jButton7.setEnabled(true);
                    this.jButton8.setEnabled(true);
                    this.jButton9.setEnabled(true);
                } else {
                    JOptionPane.showMessageDialog(null,"Contraseña Incorrecta", "Contraseña no coincide", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField9FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField9FocusLost
        // TODO add your handling code here:
        if (this.jTextField9.getText()!=""){
            viajes.BD.Clientes cliente = (viajes.BD.Clientes) clientes.buscar(this.jTextField9.getText(), 0);
            if (clientes.buscar(cliente)){
                this.jTextField10.setText(cliente.nombre+", "+cliente.apellido);
                this.jTextField11.setText(cliente.notarjeta);
                this.jTextField12.setText(cliente.telefono);
                this.jTextField13.setText(cliente.celular);
                this.jTextField14.setText(cliente.domicilio);
                this.jTextField15.setText(cliente.cpfrecuencia);
                this.jTextField16.setText(cliente.cpmonto);
            } else {
                String idnuevo = this.jTextField9.getText();
                int option = JOptionPane.showConfirmDialog(null, "Cliente no existe, ¿Desea agregarlo?","Cliente no encontrado",JOptionPane.YES_NO_OPTION);
                if (option == JOptionPane.YES_OPTION){
                    jTabbedPane1.setSelectedIndex(2);
                    jTabbedPane2.setSelectedIndex(0);
                    this.jTextField17.setText(idnuevo);
                }
            }
        }
    }//GEN-LAST:event_jTextField9FocusLost

    private void jTextField17FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField17FocusLost
        // TODO add your handling code here:
        viajes.BD.Clientes temp = (viajes.BD.Clientes) clientes.buscar(this.jTextField17.getText(), 0);
        if (clientes.buscar(temp)){
            JOptionPane.showMessageDialog(null,"Cliente ya existe, continúe para modificar datos", "Negocios - Clientes",JOptionPane.INFORMATION_MESSAGE);
            this.jButton18.setText("Actualizar");
        } else {
            this.jButton18.setText("Guardar");
        }  
    }//GEN-LAST:event_jTextField17FocusLost

    private void jTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField17ActionPerformed

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        //viajes.BD.Clientes temp = (viajes.BD.Clientes) clientes.buscar(this.jTextField17.getText(), 0);
            if (!this.jTextField17.getText().equals("") && 
                    !this.jTextField5.getText().equals("") &&
                    !this.jTextField18.getText().equals("") &&
                    !this.jTextField19.getText().equals("") &&
                    !this.jTextField6.getText().equals("") &&
                    !this.jTextField20.getText().equals("") &&
                    !this.jTextField21.getText().equals("") &&
                    !this.jTextField22.getText().equals("")){
                MClientes mclientes = new MClientes();
                if (this.jButton18.getText().equals("Guardar")){
                    viajes.BD.Clientes nuevo = new viajes.BD.Clientes(this.jTextField17.getText(),
                            this.jTextField5.getText(),
                            this.jTextField18.getText(),
                            this.jTextField19.getText(),
                            this.jTextField6.getText(),
                            this.jTextField20.getText(),
                            this.jTextField21.getText(),
                            this.jTextField22.getText(),mclientes.FRECUENCIA_UNO,"");
                    clientes.agregarAlFinal(nuevo);
                    viajes.BD.EntidadFinanciera temp = (viajes.BD.EntidadFinanciera) entidad.buscar(this.jTextField19.getText(), 3);
                    if (!entidad.buscar(temp)){
                        JOptionPane.showMessageDialog(null,"La Tarjeta asociada a Cliente no existe, proceda a crearla", "Negocios - Clientes",JOptionPane.INFORMATION_MESSAGE);
                    }
                } else {
                    viajes.BD.Clientes temp = (viajes.BD.Clientes) clientes.buscar(this.jTextField17.getText(), 0);
                    viajes.BD.Clientes nuevo = new viajes.BD.Clientes(this.jTextField17.getText(),
                            this.jTextField5.getText(),
                            this.jTextField18.getText(),
                            this.jTextField19.getText(),
                            this.jTextField6.getText(),
                            this.jTextField20.getText(),
                            this.jTextField21.getText(),
                            this.jTextField22.getText(),temp.cpfrecuencia,temp.cpmonto);
                    clientes.editarPorReferencia(temp, nuevo);
                }
            } else {
                JOptionPane.showMessageDialog(null,"Debe llenar TODOS los campos", "Negocios - Clientes",JOptionPane.INFORMATION_MESSAGE);
            }
            this.jButton18.setText("Guardar");
    }//GEN-LAST:event_jButton18ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Travels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Travels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Travels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Travels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Travels().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
