/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viajes.grafica;

import java.io.File;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import viajes.listas.Cola;
import viajes.listas.ListaSimple;
import viajes.modulos.MCarga;

/**
 *
 * @author HPBEATS
 */
public class Carga extends javax.swing.JPanel {
    MCarga carga = new MCarga();
        public Cola reservaciones = new Cola("reservaciones");
    public ListaSimple transporte = new ListaSimple("transporte");
    public ListaSimple asiento = new ListaSimple("asiento");
    public ListaSimple hoteles = new ListaSimple("hoteles");
    public ListaSimple habitacion = new ListaSimple("habitacion");
    public ListaSimple cruceros = new ListaSimple("cruceros");
    public ListaSimple camarot = new ListaSimple("camarot");
    public ListaSimple renta = new ListaSimple("renta_autos");
    public ListaSimple destinos = new ListaSimple("destinos");
    public ListaSimple lugares = new ListaSimple("lugares");
    public ListaSimple clientes = new ListaSimple("clientes");
    public ListaSimple entidad = new ListaSimple("entidad");
    public ListaSimple paquetes = new ListaSimple("paquetes"); 
    
    public String pathTransporte;
    public String pathAsiento;
    public String pathHoteles;
    public String pathHabitacion;
    public String pathCrucero;
    public String pathCamarot;
    public String pathDestino;
    public String pathLugar;
    public String pathRenta;
    public String pathClientes;
    public String pathEntidad;
    public String pathPaquetes;
    public String pathReservas;
    /**
     * Creates new form Carga
     */
    public Carga() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Presione un botón y cargue el archivo correspondiente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 13), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel4.setMinimumSize(new java.awt.Dimension(200, 450));
        jPanel4.setPreferredSize(new java.awt.Dimension(250, 450));
        jPanel4.setLayout(new java.awt.GridLayout(13, 0, 0, 5));

        jButton2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton2.setText("Aerolineas y Buses");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);

        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setText("Asiento");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);

        jButton3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton3.setText("Hoteles");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3);

        jButton4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton4.setText("Habitación");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4);

        jButton5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton5.setText("Destino Turistico");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5);

        jButton6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton6.setText("Lugar E&E");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6);

        jButton7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton7.setText("Cruceros");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton7);

        jButton8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton8.setText("Camarot");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton8);

        jButton9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton9.setText("Paquetes");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton9);

        jButton10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton10.setText("Clientes");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton10);

        jButton11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton11.setText("Renta Autos");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton11);

        jButton12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton12.setText("Reservaciones");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton12);

        jButton13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton13.setText("Entidad Financiera");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton13);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            File file = carga.openFile();

            if (file!=null){
                pathTransporte = file.getAbsolutePath();
                carga.fillList(file, transporte);
                this.jButton2.setEnabled(false);
                this.jButton2.setIcon(new ImageIcon(getClass().getResource("exito.png")));
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "No se cargo el archivo","MODULO DE CARGA",JOptionPane.ERROR_MESSAGE);
            //            Logger.getLogger(Carga.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            File file = carga.openFile();
            if (file!=null){
                pathAsiento = file.getAbsolutePath();
                carga.fillList(file, asiento);
                this.jButton1.setEnabled(false);
                this.jButton1.setIcon(new ImageIcon(getClass().getResource("exito.png")));
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "No se cargo el archivo","MODULO DE CARGA",JOptionPane.ERROR_MESSAGE);
            //            Logger.getLogger(Carga.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            File file = carga.openFile();
            if (file!=null){
                pathHoteles= file.getAbsolutePath();
                carga.fillList(file, hoteles);
                this.jButton3.setEnabled(false);
                this.jButton3.setIcon(new ImageIcon(getClass().getResource("exito.png")));
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "No se cargo el archivo","MODULO DE CARGA",JOptionPane.ERROR_MESSAGE);
            //            Logger.getLogger(Carga.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
            File file = carga.openFile();
            if (file!=null){
                pathHabitacion= file.getAbsolutePath();
                carga.fillList(file, habitacion);
                this.jButton4.setEnabled(false);
                this.jButton4.setIcon(new ImageIcon(getClass().getResource("exito.png")));
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "No se cargo el archivo","MODULO DE CARGA",JOptionPane.ERROR_MESSAGE);
            //            Logger.getLogger(Carga.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            File file = carga.openFile();
            if (file!=null){
                pathDestino= file.getAbsolutePath();
                carga.fillList(file, destinos);
                this.jButton5.setEnabled(false);
                this.jButton5.setIcon(new ImageIcon(getClass().getResource("exito.png")));
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "No se cargo el archivo","MODULO DE CARGA",JOptionPane.ERROR_MESSAGE);
            //            Logger.getLogger(Carga.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            File file = carga.openFile();
            if (file!=null){
                pathLugar = file.getAbsolutePath();
                carga.fillList(file, lugares);
                this.jButton6.setEnabled(false);
                this.jButton6.setIcon(new ImageIcon(getClass().getResource("exito.png")));
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "No se cargo el archivo","MODULO DE CARGA",JOptionPane.ERROR_MESSAGE);
            //            Logger.getLogger(Carga.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try {
            File file = carga.openFile();
            if (file!=null){
                pathCrucero= file.getAbsolutePath();
                carga.fillList(file, cruceros);
                this.jButton7.setEnabled(false);
                this.jButton7.setIcon(new ImageIcon(getClass().getResource("exito.png")));
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "No se cargo el archivo","MODULO DE CARGA",JOptionPane.ERROR_MESSAGE);
            //            Logger.getLogger(Carga.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        try {
            File file = carga.openFile();
            if (file!=null){
                pathCamarot= file.getAbsolutePath();
                carga.fillList(file, camarot);
                this.jButton8.setEnabled(false);
                this.jButton8.setIcon(new ImageIcon(getClass().getResource("exito.png")));
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "No se cargo el archivo","MODULO DE CARGA",JOptionPane.ERROR_MESSAGE);
            //            Logger.getLogger(Carga.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            File file = carga.openFile();
            if (file!=null){
                pathPaquetes= file.getAbsolutePath();
                carga.fillList(file, paquetes);
                this.jButton9.setEnabled(false);
                this.jButton9.setIcon(new ImageIcon(getClass().getResource("exito.png")));
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "No se cargo el archivo","MODULO DE CARGA",JOptionPane.ERROR_MESSAGE);
            //            Logger.getLogger(Carga.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            File file = carga.openFile();
            if (file!=null){
                pathClientes= file.getAbsolutePath();
                carga.fillList(file, clientes);
                this.jButton10.setEnabled(false);
                this.jButton10.setIcon(new ImageIcon(getClass().getResource("exito.png")));
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "No se cargo el archivo","MODULO DE CARGA",JOptionPane.ERROR_MESSAGE);
            //            Logger.getLogger(Carga.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        try {
            File file = carga.openFile();
            if (file!=null){
                pathRenta= file.getAbsolutePath();
                carga.fillList(file,renta);
                this.jButton11.setEnabled(false);
                this.jButton11.setIcon(new ImageIcon(getClass().getResource("exito.png")));
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "No se cargo el archivo","MODULO DE CARGA",JOptionPane.ERROR_MESSAGE);
            //            Logger.getLogger(Carga.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            File file = carga.openFile();
            if (file!=null){
                pathReservas = file.getAbsolutePath();
                carga.llenarCola(file, reservaciones);
                this.jButton12.setEnabled(false);
                this.jButton12.setIcon(new ImageIcon(getClass().getResource("exito.png")));
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "No se cargo el archivo","MODULO DE CARGA",JOptionPane.ERROR_MESSAGE);
            //            Logger.getLogger(Carga.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            File file = carga.openFile();
            if (file!=null){
                pathEntidad= file.getAbsolutePath();
                carga.fillList(carga.openFile(), entidad);
                this.jButton13.setEnabled(false);
                this.jButton13.setIcon(new ImageIcon(getClass().getResource("exito.png")));
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "No se cargo el archivo","MODULO DE CARGA",JOptionPane.ERROR_MESSAGE);
            //            Logger.getLogger(Carga.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton13ActionPerformed
    public JPanel getjpanel(){
        //initComponents();
        return this.jPanel4;
    }
    public void init(){
        System.out.println(jButton1);
        initComponents();
        this.jPanel4.validate();
        
        System.out.println(jPanel4);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
